apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: n10vpa3lh-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: n10vpa3lh-python 
  name: n10vpa3lh-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: n10vpa3lh-python 
